dataset:
  num_class:    20  # number of subjects
  num_per_class: 72  # images per subjects
  data_path:   "./Data/COIL20.mat" #dataset

model:
  kernel_size: [3]
  num_hidden:  [15]
  input_shape: [32, 32]
  input_shape_for_decoder: [16, 16, 15]
  pretrained_model: "checkpoint/pre_train_coil20/ck.ckpt" # pre-trained model on 38 subjects

training:
  lambdas:     [2, 1, 200] # [2, 1, 500]
  gama: 0.4
  num_epoch:    100
  num_epoch_per_print: 1
  num_epoch_pre: 15

cluster:
  d: 13     #12 13
  alpha: 7 #8 7
  ro: 0.05 # 0.04 0.05