dataset:
  num_class:    100  # number of subjects
  num_per_class: 72  # images per subjects
  data_path:   "./Data/COIL100.mat" #dataset

model:
  kernel_size: [5]
  num_hidden:  [50]
  input_shape: [32, 32]
  input_shape_for_decoder: [16, 16, 50]
  pretrained_model: "checkpoint/pre_train_coil100/ck.ckpt" # pre-trained model on 38 subjects

training:
  lambdas:     [2, 1, 30]
  gama: 0.01
  num_epoch:    55
  num_epoch_per_print: 5
  num_epoch_pre: 2700

cluster:
  d: 12
  alpha: 8
  ro: 0.04