dataset:
  num_class:    38  # number of subjects
  num_per_class: 64  # images per subjects
  data_path:   "./Data/YaleBCrop025.mat" #dataset

model:
  kernel_size: [5, 3, 3]
  num_hidden:  [10, 20, 30]
  input_shape: [42, 48]
  input_shape_for_decoder: [6, 6, 30]
  pretrained_model: "checkpoint/pre_train_yaleb/ck.ckpt" # pre-trained model on 38 subjects

training:
  lambdas:     [1, 1, 6.3]
  gama: 0.5
  num_epoch:    5000 # 2100
  num_epoch_per_print: 20
  num_epoch_pre: 2500 # 25

cluster:
  d: 10
  alpha: 3.5
  ro: 0.08