dataset:
  num_class:    10  # number of subjects
  num_per_class: 100  # images per subjects
  data_path:   "./Data/mnist1000.mat" #dataset

model:
  kernel_size: [5, 3, 3]
  num_hidden:  [15, 10, 5]
  input_shape: [28, 28]
  input_shape_for_decoder: [4, 4, 5]
  pretrained_model: "checkpoint/pre_train_mnist/ck.ckpt" # pre-trained model on 38 subjects

training:
  lambdas:     [1.0, 7, 2.5]
  gama: 0.1 # 0.1-65%
  num_epoch:   140
  num_epoch_per_print: 10
  num_epoch_pre: 50 # 1000

cluster:
  d: 7 # 20  5      5
  alpha: 25 # 10  1  25
  ro: 0.1