dataset:
  num_class:    20  # number of subjects
  num_per_class: 24  # images per subjects
  data_path:   "./Data/umist-32-32.mat" #dataset

model:
  kernel_size: [5, 3, 3]
  num_hidden:  [15, 10, 5] # [20, 10, 5]
  input_shape: [32, 32]
  input_shape_for_decoder: [4, 4, 5]
  pretrained_model: "checkpoint/pre_train_umist/ck.ckpt" # pre-trained model on 38 subjects

training:
  lambdas:     [2, 1, 30]
  gama: 0.01
  num_epoch:    700
  num_epoch_per_print: 1
  num_epoch_pre: 10

cluster:
  d: 5
  alpha: 8
  ro: 1